2022-06-07 00:07:42,568 ERROR: <client.py> <self.quit()>: [Errno 9] Bad file descriptor
2022-06-07 00:07:42,569 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: [Errno 104] Connection reset by peer
2022-06-07 00:09:28,315 ERROR: <client.py> <self.quit()>: [Errno 9] Bad file descriptor
2022-06-07 00:09:30,012 ERROR: <client.py> <self.quit()>: [Errno 9] Bad file descriptor
2022-06-07 00:11:29,113 ERROR: <client.py> <self.print_menu()>: object of type 'Queue' has no len()
2022-06-07 00:12:06,202 ERROR: <client.py> <self.quit()>: [Errno 9] Bad file descriptor
2022-06-07 00:12:06,203 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: [Errno 104] Connection reset by peer
2022-06-07 00:12:07,417 ERROR: <client.py> <self.quit()>: [Errno 9] Bad file descriptor
2022-06-07 00:13:56,286 ERROR: <client.py> <self.print_menu()>: object of type 'Queue' has no len()
2022-06-07 00:16:31,909 ERROR: <client.py> <self.quit()>: [Errno 9] Bad file descriptor
2022-06-07 00:17:32,660 ERROR: <client.py> <except KeyboardInterrupt:>: Not connected
2022-06-07 00:17:32,692 ERROR: <client.py> <self.quit()>: [Errno 9] Bad file descriptor
